Flint: SparkRDD< T > Class Template Reference
SparkRDD< T > Class Template Reference abstract
#include <KrapsRDD.h>
Public Member Functions
bool next (T &row)
SparkRDD (JNIEnv *env, jint no)
virtual bool getNext (T &record)=0
template<bool(*)(T const &) predicate>
RDD< T > * filter ()
template<class K , class V , void(*)(Pair< K, V > &out, T const &in) map, void(*)(V &dst, V const &src) reduce>
RDD< Pair< K, V > > * mapReduce (size_t estimation=UNKNOWN_ESTIMATION)
template<class S , void(*)(S &state, T const &in) accumulate, void(*)(S &state, S const &in) combine>
RDD< S > * reduce (S const &initState)
template<class P , void(*)(P &out, T const &in) projection>
RDD< P > * project ()
template<int(*)(T const *a, T const *b) compare>
RDD< T > * sort (size_t estimation=UNKNOWN_ESTIMATION)
template<int(*)(T const *a, T const *b) compare>
RDD< T > * top (size_t n)
template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey>
RDD< Join< T, I > > * join (RDD< I > *with, size_t estimation=UNKNOWN_ESTIMATION, JoinKind kind=InnerJoin)
template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey>
RDD< T > * semijoin (RDD< I > *with, size_t estimation=UNKNOWN_ESTIMATION, JoinKind kind=InnerJoin)
virtual RDD< T > * replicate ()
T result (T const &defaultValue)
void output (FILE *out)
Public Attributes
T elem
Detailed Description
template<class T>
class SparkRDD< T >
Proxy class for accessing Spark RDD from Kraps
Constructor & Destructor Documentation
template<class T > SparkRDD< T >::SparkRDD (JNIEnv * env, jint no) inline
SparkRDD constructor
Parameters
env JNI environment
no index of RDD in input array
Member Function Documentation
template<class T > template<bool(*)(T const &) predicate> RDD< T > * RDD< T >::filter () inline inherited
Filter input RDD
Returns
RDD with records matching predicate
template<class T> virtual bool RDD< T >::getNext (T & record) pure virtual inherited
Virtual iteration method which should be overriden by derived classes. Because of virtual call overhead getNext method is not actually used in RDD implementations, instead of it them invokes next() method using template mechanism. But appliation can use this method to access arbitrary RDD.
Parameters
record [out] placeholder for the next record
Returns
true if there is next record, false otherwise
Implemented in CachedRDD< T >, ShuffleJoinRDD< O, I, K, outerKey, innerKey, ORdd, IRdd >, HashSemiJoinRDD< O, I, K, outerKey, innerKey, ORdd, IRdd >, HashJoinRDD< O, I, K, outerKey, innerKey, ORdd, IRdd >, TopRDD< T, compare, Rdd >, SortRDD< T, compare, Rdd >, ProjectRDD< T, P, project, Rdd >, MapReduceRDD< T, K, V, map, reduce, Rdd >, ReduceRDD< T, S, accumulate, combine, Rdd >, FilterRDD< T, predicate, Rdd >, DirRDD< T >, FileRDD< T >, BufferRDD< T >, GatherRDD< T >, and GatherRDD< O >.
Referenced by RDD< Join< O, I > >::next().
template<class T > template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey> RDD< Join< T, I > > * RDD< T >::join (RDD< I > * with, size_t estimation = UNKNOWN_ESTIMATION, JoinKind kind = InnerJoin) inherited
Join of two RDDs. Inner join returns pairs of matches records in outer and inner table. Outer join also returns records from outer table for which there are matching in inner table.
Parameters
with inner join table
estimation estimation for number of joined records
kind join kind (inner/outer join)
template<class T > template<class K , class V , void(*)(Pair< K, V > &out, T const &in) map_f, void(*)(V &dst, V const &src) reduce_f> RDD< Pair< K, V > > * RDD< T >::mapReduce (size_t estimation = UNKNOWN_ESTIMATION) inline inherited
Perfrom map-reduce
Parameters
estimation esimation for number of pairs
Returns
RDD with <key,value> pairs
template<class T > bool SparkRDD< T >::next (T & row) inline
Get next row
Parameters
row [out] placeholder for next row
Returns
true if there is next record, false otherwise
template<class T > void RDD< T >::output (FILE * out) inherited
Print RDD records to the stream
Parameters
out output stream
References Cluster::barrier(), Cluster::getQueue(), and Cluster::isCoordinator().
template<class T > template<class P , void(*)(P &out, T const &in) projection> RDD< P > * RDD< T >::project () inline inherited
Map records of input RDD
Returns
projection of the input RDD.
template<class T > template<class S , void(*)(S &state, T const &in) accumulate, void(*)(S &state, S const &partial) combine> RDD< S > * RDD< T >::reduce (S const & initState) inline inherited
Perform aggregation of input RDD
Parameters
initState initial aggregate value
Returns
RDD with aggregated value
template<class T > RDD< T > * RDD< T >::replicate () inline virtual inherited
Replicate data between all nodes. Broadcast local RDD data to all nodes and gather data from all nodes. As a result all nodes get the same replicas of input data
Returns
replicated RDD, combining data from all nodes
Reimplemented in DirRDD< T >, and FileRDD< T >.
Referenced by FileRDD< T >::replicate(), and DirRDD< T >::replicate().
template<class T> T RDD< T >::result (T const & defaultValue) inline inherited
Get single record from input RDD or substitute it with default value of RDD is empty. This method is usful for obtaining aggregation result
Returns
Single record from input RDD or substitute it with default value of RDD is empty.
template<class T > template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey> RDD< T > * RDD< T >::semijoin (RDD< I > * with, size_t estimation = UNKNOWN_ESTIMATION, JoinKind kind = InnerJoin) inherited
Semijoin of two RDDs. Semijoin find matched records in both tables but returns only records from outer table. Antijoin returns only this records of outer table for which there are no matching in inner table.
Parameters
with inner join table
estimation estimation for number of joined records
kind join kind (inner/anti join)
template<class T > template<int(*)(T const *a, T const *b) compare> RDD< T > * RDD< T >::sort (size_t estimation = UNKNOWN_ESTIMATION) inline inherited
Sort input RDD
Parameters
estimation estimation for number of records in RDD
Returns
RDD with sorted records
template<class T > template<int(*)(T const *a, T const *b) compare> RDD< T > * RDD< T >::top (size_t n) inline inherited
Find top N records according to provided comparison function
Parameters
n number of returned top records
Returns
RDD with up to N top records
Member Data Documentation
template<class T> T RDD< T >::elem inherited
RDD element. It is used for getting RDD elementtype using typeof macro
The documentation for this class was generated from the following file:
KrapsRDD.h