Flint: Cluster Class Reference
Cluster Class Reference
#include <cluster.h>
Public Member Functions
FILE * openTempFile (char const *prefix, qid_t qid, size_t no, char const *mode="r")
bool isCoordinator ()
Queue * getQueue (MessageHandler *hnd=NULL)
void barrier ()
void send (size_t node, Queue *queue, Buffer *buf)
bool isLocalNode (char const *host)
Cluster (size_t nodeId, size_t nHosts, char **hosts, size_t nQueues=64, size_t bufferSize=4 *64 *1024, size_t recvQueueSize=4 *64 *1024 *1024, size_t sendQueueSize=4 *4 *1024 *1024, size_t syncInterval=64 *1024 *1024, size_t broadcastJoinThreshold=10000, size_t inmemJoinThreshold=10000000, char const *tmp="/tmp", bool sharedNothing=true, size_t split=1)
Public Attributes
size_t const nNodes
size_t const maxQueues
size_t const nodeId
size_t const bufferSize
size_t const syncInterval
size_t const broadcastJoinThreshold
size_t const inmemJoinThreshold
size_t const split
bool const sharedNothing
char const * tmpDir
Socket ** sockets
Queue ** recvQueues
Queue ** sendQueues
Thread ** senders
char ** hosts
qid_t qid
Thread * receiver
bool shutdown
size_t nExecutorsPerHost
void * userData
Mutex mutex
Event cond
Static Public Attributes
static Cluster ** nodes
static ThreadLocal< Cluster > instance
Detailed Description
Main cluster class.
Constructor & Destructor Documentation
Cluster::Cluster (size_t nodeId, size_t nHosts, char ** hosts, size_t nQueues = 64, size_t bufferSize = 4 *64 *1024, size_t recvQueueSize = 4 *64 *1024 *1024, size_t sendQueueSize = 4 *4 *1024 *1024, size_t syncInterval = 64 *1024 *1024, size_t broadcastJoinThreshold = 10000, size_t inmemJoinThreshold = 10000000, char const * tmp = "/tmp", bool sharedNothing = true, size_t split = 1)
Cluster constructor
Parameters:
nodeId identifier of this cluster node (nodes are enumerated from 0)
nHosts number of nodes in clisters
hosts addresses of cluster node. Each address includes host name and port separated by column, i.e. "localhost:5011"
nQueues maximal number of receive queues (64)
bufferSize size of buffer used for internode communication (256kb)
recvQueueSize size of receive queue (256Mb)
sendQueueSize size of send queue (16Mb)
syncInterval synchorinization inerval (amount of bytes after which PING message is sent to synchronize data producer and consumer (64Mb)
broadcastJoinThreshold threshold for choosing broadcast of inner table for join rather than shuffle method (10 000)
inmemJoinThreshold threshold for choosing shuffling to files instead of in-memory join (10 000 000)
tmp directory for creating shuffling files ("/tmp")
sharedNothing trues if each nodes is given its own local files, false if files in DFS are shared by all nodes
split split factor. Using split factor greater than 1 it is posisble to spawn more cluster nodes than there are physical partitions (files)
Member Function Documentation
void Cluster::barrier ()
Set barrier: syncronize execution of all nodes
Referenced by RDD< T >::output().
Queue* Cluster::getQueue (MessageHandler * hnd = NULL)
Get new queue. It is expected that queues are created in the same order by all nodes, so them are given same queue identifiers. This is why it is possible to use QID to identify recipient at target node.
Parameters:
hnd optional message handler used for push-style processing for this queue
Referenced by RDD< T >::output().
bool Cluster::isCoordinator () [inline]
Check if this node is coordinator. Coordinator is forst node in the cluster and it is used to collect all local results from other nodes
Referenced by RDD< T >::output().
bool Cluster::isLocalNode (char const * host)
Check if sepcified address corresponds to local node
Parameters:
host host address
Returns:
true if host is localhost or matchs with name returned by uname
void Cluster::send (size_t node, Queue * queue, Buffer * buf)
Send message to the node or place it in locasl queue
Parameters:
node destination node
queue if node is self node, then message is placed directly in this queue, otherwise it is sent to the remote node with qid (queue identifier) taken from this queue
buf message to be delivered
The documentation for this class was generated from the following file:
cluster.h