Flint: RDD< T > Class Template Reference
RDD< T > Class Template Reference
#include <rdd.h>
Public Member Functions
virtual bool next (T &record)=0
template<bool(*)(T const &) predicate>
RDD< T > * filter ()
template<class K , class V , void(*)(Pair< K, V > &out, T const &in) map, void(*)(V &dst, V const &src) reduce>
RDD< Pair< K, V > > * mapReduce (size_t estimation)
template<class S , void(*)(S &state, T const &in) accumulate, void(*)(S &state, S const &in) combine>
RDD< S > * reduce (S const &initState)
template<class P , void(*)(P &out, T const &in) projection>
RDD< P > * project ()
template<int(*)(T const *a, T const *b) compare>
RDD< T > * sort (size_t estimation)
template<int(*)(T const *a, T const *b) compare>
RDD< T > * top (size_t n)
template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey>
RDD< Join< T, I > > * join (RDD< I > *with, size_t estimation, JoinKind kind=InnerJoin)
template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey>
RDD< T > * semijoin (RDD< I > *with, size_t estimation, JoinKind kind=InnerJoin)
virtual RDD< T > * replicate ()
T result (T const &defaultValue)
void output (FILE *out)
Detailed Description
template<class T>
class RDD< T >
Abstract RDD (Resilient Distributed Dataset)
Member Function Documentation
template<class T > template<bool(*)(T const &) predicate> RDD< T > * RDD< T >::filter () [inline]
Filter input RDD
Returns:
RDD with records matching predicate
template<class T > template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey> RDD< Join< T, I > > * RDD< T >::join (RDD< I > * with, size_t estimation, JoinKind kind = InnerJoin)
Left join two RDDs. Inner join returns pairs of matches records in outer and inner table. Outer join also returns records from outer table for which there are matching in inner table.
Parameters:
with inner join table
estimation estimation for number of joined records
kind join kind (inner/outer join)
template<class T > template<class K , class V , void(*)(Pair< K, V > &out, T const &in) map_f, void(*)(V &dst, V const &src) reduce_f> RDD< Pair< K, V > > * RDD< T >::mapReduce (size_t estimation) [inline]
Perfrom map-reduce
Parameters:
estimation esimation for number of pairs
Returns:
RDD with <key,value> pairs
template<class T> virtual bool RDD< T >::next (T & record) [pure virtual]
Main RDD method for iterating thoough records
Parameters:
record [out] placeholder for the next record
Returns:
true if there is next record, false otherwise
Implemented in CachedRDD< T >, ShuffleJoinRDD< O, I, K, outerKey, innerKey >, HashSemiJoinRDD< O, I, K, outerKey, innerKey >, HashJoinRDD< O, I, K, outerKey, innerKey >, TopRDD< T, compare >, SortRDD< T, compare >, ProjectRDD< T, P, project >, MapReduceRDD< T, K, V, map, reduce >, ReduceRDD< T, S, accumulate, combine >, FilterRDD< T, predicate >, DirRDD< T >, FileRDD< T >, GatherRDD< T >, and SparkRDD< T >.
Referenced by HashJoinRDD< O, I, K, outerKey, innerKey >::next(), HashSemiJoinRDD< O, I, K, outerKey, innerKey >::next(), and RDD< I >::result().
template<class T > void RDD< T >::output (FILE * out)
Print RDD records to the stream
Parameters:
out output stream
References Cluster::barrier(), Cluster::getQueue(), Cluster::isCoordinator(), and GatherRDD< T >::next().
template<class T > template<class P , void(*)(P &out, T const &in) projection> RDD< P > * RDD< T >::project () [inline]
Map records of input RDD
Returns:
projection of the input RDD.
template<class T > template<class S , void(*)(S &state, T const &in) accumulate, void(*)(S &state, S const &partial) combine> RDD< S > * RDD< T >::reduce (S const & initState) [inline]
Perform aggregation of input RDD
Parameters:
initState initial aggregate value
Returns:
RDD with aggregated value
template<class T > RDD< T > * RDD< T >::replicate () [inline, virtual]
Replicate data between all nodes. Broadcast local RDD data to all nodes and gather data from all nodes. As a result all nodes get the same replicas of input data
Returns:
replicated RDD, combining data from all nodes
Reimplemented in DirRDD< T >, and FileRDD< T >.
Referenced by HashJoinRDD< O, I, K, outerKey, innerKey >::next(), and HashSemiJoinRDD< O, I, K, outerKey, innerKey >::next().
template<class T> T RDD< T >::result (T const & defaultValue) [inline]
Get single record from input RDD or substitute it with default value of RDD is empty. This method is usful for obtaining aggregation result
Returns:
Single record from input RDD or substitute it with default value of RDD is empty.
template<class T > template<class I , class K , void(*)(K &key, T const &outer) outerKey, void(*)(K &key, I const &inner) innerKey> RDD< T > * RDD< T >::semijoin (RDD< I > * with, size_t estimation, JoinKind kind = InnerJoin)
Left simijoin two RDDs. Semijoin find matched records in both tables but returns only records from outer table. Antijoin returns only this records of outer table for which there are no matching in inner table.
Parameters:
with inner join table
estimation estimation for number of joined records
kind join kind (inner/anti join)
template<class T > template<int(*)(T const *a, T const *b) compare> RDD< T > * RDD< T >::sort (size_t estimation) [inline]
Sort input RDD
Parameters:
estimation estimation for number of records in RDD
Returns:
RDD with sorted records
template<class T > template<int(*)(T const *a, T const *b) compare> RDD< T > * RDD< T >::top (size_t n) [inline]
Find top N records according to provided comparison function
Parameters:
n number of returned top records
Returns:
RDD with up to N top records
The documentation for this class was generated from the following file:
rdd.h