Flint: Buffer Struct Reference
Buffer Struct Reference
#include <cluster.h>
Public Member Functions
Buffer (MessageKind type, qid_t id, size_t len=0)
void * operator new (size_t hdrSize, size_t bufSize)
void operator delete (void *ptr, size_t size)
void operator delete (void *ptr)
void release ()
Static Public Member Functions
static Buffer * create (qid_t qid, size_t size, MessageKind type=MSG_DATA)
static Buffer * eof (qid_t qid)
static Buffer * barrier (qid_t qid)
static Buffer * ping (qid_t qid)
Public Attributes
uint32_t compressedSize
uint32_t size
uint16_t node
uint16_t qid
uint16_t kind
uint16_t refCount
char data [1]
Detailed Description
Buffer is the main unit of echanging data between node in Flint. Although RDD is processning and traversing individual records, when data needs to be sent through network, records are packed into buffer and buffer is delivier to the destination node.
Constructor & Destructor Documentation
Buffer::Buffer (MessageKind type, qid_t id, size_t len = 0) [inline]
Buffer constructor
Parameters:
type message type
id queue ID (needed to locate recipient queue at target node)
len buffer data size (not including header)
Referenced by create().
Member Function Documentation
static Buffer* Buffer::barrier (qid_t qid) [inline, static]
Create buffer with barries message
Parameters:
qid queue ID (needed to locate recipient queue at target node)
Returns:
new barrier message
References create().
static Buffer* Buffer::create (qid_t qid, size_t size, MessageKind type = MSG_DATA) [inline, static]
Create new buffer of specified kind and size
Parameters:
qid queue ID (needed to locate recipient queue at target node)
size buffer data size (not including header)
type message type
Returns:
created buffer
References Buffer().
Referenced by barrier(), eof(), and ping().
static Buffer* Buffer::eof (qid_t qid) [inline, static]
Create buffer with EOF (End-Of-File) message
Parameters:
qid queue ID (needed to locate recipient queue at target node)
Returns:
new EOF message
References create().
static Buffer* Buffer::ping (qid_t qid) [inline, static]
Create buffer with ping message. Ping messages are used to synchronize data consumers and produces and so avoid queueus overflow
Parameters:
qid queue ID (needed to locate recipient queue at target node)
Returns:
new ping message
References create().
void Buffer::release () [inline]
Release buffer. Flint associates reference counter with each buffer to impkement shared pointers to the buffers. This method allows to delete buffer when it is not needed to anybody (there are no more references to the buffer).
Referenced by GatherRDD< T >::next().
The documentation for this struct was generated from the following file:
cluster.h